DECLARE V_HISTLONG LONG;
        V_CODCOLIGADA INT;
        V_IDMOV INT;
BEGIN
 
    V_CODCOLIGADA := 2;
    V_IDMOV := 14912;
    
    SELECT HISTORICOLONGO INTO V_HISTLONG
    FROM TMOVHISTORICO
    WHERE CODCOLIGADA = V_CODCOLIGADA
    AND IDMOV = V_IDMOV;
    
    V_HISTLONG := FNC_RETIRA_ACENTUACAO(V_HISTLONG) || ' -- ALTERADO';
    
    UPDATE TMOVHISTORICO SET HISTORICOLONGO = V_HISTLONG 
    WHERE CODCOLIGADA = V_CODCOLIGADA
    AND IDMOV = V_IDMOV;
    
    COMMIT;
END;
