CREATE OR REPLACE FUNCTION RM.BLOB_VARCHAR(B BLOB)
RETURN CLOB IS
  C CLOB;
  N NUMBER;
BEGIN
  IF (B IS NULL) THEN
    RETURN NULL;
  END IF;
  IF (LENGTH(B)=0) THEN
    RETURN EMPTY_CLOB();
  END IF;
  DBMS_LOB.CREATETEMPORARY(C,TRUE);
  N:=1;
  WHILE (N+32767<=LENGTH(B)) LOOP
    DBMS_LOB.WRITEAPPEND(C,32767,UTL_RAW.CAST_TO_VARCHAR2(DBMS_LOB.SUBSTR(B,32767,N)));
    N:=N+32767;
  END LOOP;
  DBMS_LOB.WRITEAPPEND(C,LENGTH(B)-N+1,UTL_RAW.CAST_TO_VARCHAR2(DBMS_LOB.SUBSTR(B,LENGTH(B)-N+1,N)));
  RETURN C;
END;
/