SELECT  HORA, 
        TO_NUMBER(SUBSTR(HORA,1,INSTR(HORA,':')-1)) HORA,
        TO_NUMBER(SUBSTR(HORA,(INSTR(HORA,':')+1),2)) MINUTO,
        (TO_NUMBER(SUBSTR(HORA,1,INSTR(HORA,':')-1)) +
         TO_NUMBER(SUBSTR(HORA,(INSTR(HORA,':')+1),2))) AS VLRDECIMAL
FROM ZPFFINANC_IMP




Ex: Remover espaços em branco após o nome do dependente:

SELECT  NOME, 
        SUBSTR(NOME,1,INSTR(NOME,'  ')-1), -- REMOVE ESPAÇOS APÓS O NOME
        LENGTH(SUBSTR(NOME,1,INSTR(NOME,'  ')-1))
FROM PFDEPEND
WHERE CODCOLIGADA = 10

UPDATE PFDEPEND SET NOME = SUBSTR(NOME,1,INSTR(NOME,'  ')-1)
WHERE CODCOLIGADA = 10
