Sequence
Identity
Auto Incremento


Prezados,
 
Na versão do Oracle que estamos, não é permitido criar uma coluna do tipo IDENTITY (auto incremento), como no SQL Server.
Com isso, precisamos realizar os procedimentos abaixo:
IDSINC 
--1) CRIAR UMA SEQUENCE
CREATE SEQUENCE IDENTITY_EDUC
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 99999999999
    NOCACHE
    CYCLE;
 
--2) CRIAR UMA TABELA
CREATE TABLE ZIDENTITY (
    ID NUMBER,
    NOME VARCHAR2(50) NOT NULL, -- EXEMPLO DE CAMPO NOT NULL
    DESCRICAO VARCHAR2(50),
    CONSTRAINT PK_ZIDENTITY PRIMARY KEY (ID) -- EXEMPLO DE CHAVE PRIMÁRIA
);
 
-- 3) INSERINDO REGISTRO
INSERT INTO ZIDENTITY (ID, NOME, DESCRICAO)
VALUES (IDENTITY_EDUC.NEXTVAL, 'TESTE'||' - '||TO_CHAR(IDENTITY_EDUC.NEXTVAL), 'TESTE');
 
-- 4) ANALISANDO A TABELA
SELECT *
FROM ZIDENTITY
